/*
 * Clever API
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DistrictContact;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * District
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-10-25T09:14:56.929Z")
public class District {
  @SerializedName("district_contact")
  private DistrictContact districtContact = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("last_sync")
  private String lastSync = null;

  @SerializedName("launch_date")
  private LocalDate launchDate = null;

  @SerializedName("login_methods")
  private List<String> loginMethods = null;

  @SerializedName("mdr_number")
  private String mdrNumber = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("nces_id")
  private String ncesId = null;

  @SerializedName("pause_end")
  private String pauseEnd = null;

  @SerializedName("pause_start")
  private String pauseStart = null;

  @SerializedName("portal_url")
  private String portalUrl = null;

  @SerializedName("sis_type")
  private String sisType = null;

  /**
   * Gets or Sets state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    RUNNING("running"),
    
    PENDING("pending"),
    
    ERROR("error"),
    
    PAUSED("paused"),
    
    EMPTY(""),
    
    SUCCESS("success");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StateEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  public District districtContact(DistrictContact districtContact) {
    this.districtContact = districtContact;
    return this;
  }

   /**
   * Get districtContact
   * @return districtContact
  **/
  @ApiModelProperty(value = "")
  public DistrictContact getDistrictContact() {
    return districtContact;
  }

  public void setDistrictContact(DistrictContact districtContact) {
    this.districtContact = districtContact;
  }

  public District error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public District id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public District lastSync(String lastSync) {
    this.lastSync = lastSync;
    return this;
  }

   /**
   * Get lastSync
   * @return lastSync
  **/
  @ApiModelProperty(value = "")
  public String getLastSync() {
    return lastSync;
  }

  public void setLastSync(String lastSync) {
    this.lastSync = lastSync;
  }

  public District launchDate(LocalDate launchDate) {
    this.launchDate = launchDate;
    return this;
  }

   /**
   * Get launchDate
   * @return launchDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getLaunchDate() {
    return launchDate;
  }

  public void setLaunchDate(LocalDate launchDate) {
    this.launchDate = launchDate;
  }

  public District loginMethods(List<String> loginMethods) {
    this.loginMethods = loginMethods;
    return this;
  }

  public District addLoginMethodsItem(String loginMethodsItem) {
    if (this.loginMethods == null) {
      this.loginMethods = new ArrayList<String>();
    }
    this.loginMethods.add(loginMethodsItem);
    return this;
  }

   /**
   * Get loginMethods
   * @return loginMethods
  **/
  @ApiModelProperty(value = "")
  public List<String> getLoginMethods() {
    return loginMethods;
  }

  public void setLoginMethods(List<String> loginMethods) {
    this.loginMethods = loginMethods;
  }

  public District mdrNumber(String mdrNumber) {
    this.mdrNumber = mdrNumber;
    return this;
  }

   /**
   * Get mdrNumber
   * @return mdrNumber
  **/
  @ApiModelProperty(value = "")
  public String getMdrNumber() {
    return mdrNumber;
  }

  public void setMdrNumber(String mdrNumber) {
    this.mdrNumber = mdrNumber;
  }

  public District name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public District ncesId(String ncesId) {
    this.ncesId = ncesId;
    return this;
  }

   /**
   * Get ncesId
   * @return ncesId
  **/
  @ApiModelProperty(value = "")
  public String getNcesId() {
    return ncesId;
  }

  public void setNcesId(String ncesId) {
    this.ncesId = ncesId;
  }

  public District pauseEnd(String pauseEnd) {
    this.pauseEnd = pauseEnd;
    return this;
  }

   /**
   * Get pauseEnd
   * @return pauseEnd
  **/
  @ApiModelProperty(value = "")
  public String getPauseEnd() {
    return pauseEnd;
  }

  public void setPauseEnd(String pauseEnd) {
    this.pauseEnd = pauseEnd;
  }

  public District pauseStart(String pauseStart) {
    this.pauseStart = pauseStart;
    return this;
  }

   /**
   * Get pauseStart
   * @return pauseStart
  **/
  @ApiModelProperty(value = "")
  public String getPauseStart() {
    return pauseStart;
  }

  public void setPauseStart(String pauseStart) {
    this.pauseStart = pauseStart;
  }

  public District portalUrl(String portalUrl) {
    this.portalUrl = portalUrl;
    return this;
  }

   /**
   * Get portalUrl
   * @return portalUrl
  **/
  @ApiModelProperty(value = "")
  public String getPortalUrl() {
    return portalUrl;
  }

  public void setPortalUrl(String portalUrl) {
    this.portalUrl = portalUrl;
  }

  public District sisType(String sisType) {
    this.sisType = sisType;
    return this;
  }

   /**
   * Get sisType
   * @return sisType
  **/
  @ApiModelProperty(value = "")
  public String getSisType() {
    return sisType;
  }

  public void setSisType(String sisType) {
    this.sisType = sisType;
  }

  public District state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    District district = (District) o;
    return Objects.equals(this.districtContact, district.districtContact) &&
        Objects.equals(this.error, district.error) &&
        Objects.equals(this.id, district.id) &&
        Objects.equals(this.lastSync, district.lastSync) &&
        Objects.equals(this.launchDate, district.launchDate) &&
        Objects.equals(this.loginMethods, district.loginMethods) &&
        Objects.equals(this.mdrNumber, district.mdrNumber) &&
        Objects.equals(this.name, district.name) &&
        Objects.equals(this.ncesId, district.ncesId) &&
        Objects.equals(this.pauseEnd, district.pauseEnd) &&
        Objects.equals(this.pauseStart, district.pauseStart) &&
        Objects.equals(this.portalUrl, district.portalUrl) &&
        Objects.equals(this.sisType, district.sisType) &&
        Objects.equals(this.state, district.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(districtContact, error, id, lastSync, launchDate, loginMethods, mdrNumber, name, ncesId, pauseEnd, pauseStart, portalUrl, sisType, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class District {\n");
    
    sb.append("    districtContact: ").append(toIndentedString(districtContact)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSync: ").append(toIndentedString(lastSync)).append("\n");
    sb.append("    launchDate: ").append(toIndentedString(launchDate)).append("\n");
    sb.append("    loginMethods: ").append(toIndentedString(loginMethods)).append("\n");
    sb.append("    mdrNumber: ").append(toIndentedString(mdrNumber)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ncesId: ").append(toIndentedString(ncesId)).append("\n");
    sb.append("    pauseEnd: ").append(toIndentedString(pauseEnd)).append("\n");
    sb.append("    pauseStart: ").append(toIndentedString(pauseStart)).append("\n");
    sb.append("    portalUrl: ").append(toIndentedString(portalUrl)).append("\n");
    sb.append("    sisType: ").append(toIndentedString(sisType)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

