/*
 * Clever API
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Contact;
import io.swagger.client.model.DistrictAdmin;
import io.swagger.client.model.Staff;
import io.swagger.client.model.Student;
import io.swagger.client.model.Teacher;
import java.io.IOException;

/**
 * Roles
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-10-25T09:14:56.929Z")
public class Roles {
  @SerializedName("contact")
  private Contact contact = null;

  @SerializedName("district_admin")
  private DistrictAdmin districtAdmin = null;

  @SerializedName("staff")
  private Staff staff = null;

  @SerializedName("student")
  private Student student = null;

  @SerializedName("teacher")
  private Teacher teacher = null;

  public Roles contact(Contact contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @ApiModelProperty(value = "")
  public Contact getContact() {
    return contact;
  }

  public void setContact(Contact contact) {
    this.contact = contact;
  }

  public Roles districtAdmin(DistrictAdmin districtAdmin) {
    this.districtAdmin = districtAdmin;
    return this;
  }

   /**
   * Get districtAdmin
   * @return districtAdmin
  **/
  @ApiModelProperty(value = "")
  public DistrictAdmin getDistrictAdmin() {
    return districtAdmin;
  }

  public void setDistrictAdmin(DistrictAdmin districtAdmin) {
    this.districtAdmin = districtAdmin;
  }

  public Roles staff(Staff staff) {
    this.staff = staff;
    return this;
  }

   /**
   * Get staff
   * @return staff
  **/
  @ApiModelProperty(value = "")
  public Staff getStaff() {
    return staff;
  }

  public void setStaff(Staff staff) {
    this.staff = staff;
  }

  public Roles student(Student student) {
    this.student = student;
    return this;
  }

   /**
   * Get student
   * @return student
  **/
  @ApiModelProperty(value = "")
  public Student getStudent() {
    return student;
  }

  public void setStudent(Student student) {
    this.student = student;
  }

  public Roles teacher(Teacher teacher) {
    this.teacher = teacher;
    return this;
  }

   /**
   * Get teacher
   * @return teacher
  **/
  @ApiModelProperty(value = "")
  public Teacher getTeacher() {
    return teacher;
  }

  public void setTeacher(Teacher teacher) {
    this.teacher = teacher;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Roles roles = (Roles) o;
    return Objects.equals(this.contact, roles.contact) &&
        Objects.equals(this.districtAdmin, roles.districtAdmin) &&
        Objects.equals(this.staff, roles.staff) &&
        Objects.equals(this.student, roles.student) &&
        Objects.equals(this.teacher, roles.teacher);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contact, districtAdmin, staff, student, teacher);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Roles {\n");
    
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    districtAdmin: ").append(toIndentedString(districtAdmin)).append("\n");
    sb.append("    staff: ").append(toIndentedString(staff)).append("\n");
    sb.append("    student: ").append(toIndentedString(student)).append("\n");
    sb.append("    teacher: ").append(toIndentedString(teacher)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

